source 'https://github.com/cocoapods/specs.git'
source 'https://github.com/cosmos33/MMSpecs'
source 'https://git.wemomo.com/ios/Specs.git'
source 'https://git.wemomo.com/base/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!

target :PhotonIM do
    # --------------------- 第三方Pod -----------------------
    pod 'AFNetworking', '3.2.1'
    pod 'SDWebImage', '4.4.7'
    pod 'Masonry', '1.1.0'
    pod 'YYWebImage'
    pod 'MJRefresh', '3.2.0'
    pod 'SVProgressHUD', '2.2.5'
    pod 'MBProgressHUD', '1.1.0'
    pod 'FMDB', '2.7.2'
    pod 'MMKV','1.0.22'
    pod 'MMBase-iOS'
#    pod 'PhotonPushSDK',:git => 'https://github.com/zhanghesheng/PhotonPushSDK.git',:tag => '1.1.1'
#    pod 'PhotonPushSDK',:path => '../../TOB_PUSH/PhotonPushSDK'
#    pod 'PhotonIMSDK',:git => 'https://github.com/zhanghesheng/PhotonIMSDK-iOS.git',:tag => '2.2.14.1'
#    pod 'PhotonIMSDK',:path => '../'
    pod 'PhotonPushSDK','1.1.2'
     pod 'PhotonIMSDK','2.2.14.1'
    pod 'GrowingAutoTrackKit'
    pod 'Rifle'
    pod 'Protobuf','~>3.6.1'
    pod 'MMFileService' ,'1.3.0'
    pod 'PhotonHTTPDNS'

end
